name: "Cherry-pick from rc to develop"

on:
  pull_request:
    branches:
      - release/candidate
    types:
      - closed

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SUBMODULE_NAME: this-is-another-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Append -cherry-pick to branch name
        id: extract
        run: |
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          NEW_BRANCH_NAME="${PR_BRANCH}-cherry-pick"
          echo "New branch name: $NEW_BRANCH_NAME"
          echo "newBranchName=$NEW_BRANCH_NAME" >> $GITHUB_ENV

      - name: Check if changes only in submodule
        id: check_changes
        run: |
          NUM_CHANGES=$(git diff origin/develop --name-only | grep -v '^${{ env.SUBMODULE_NAME }}/' | wc -l)
          if [ "$NUM_CHANGES" -gt 0 ]; then
            echo "::set-output name=shouldCherryPick::true"
          else
            echo "No changes outside of ${{ env.SUBMODULE_NAME }} submodule, skipping cherry-pick"
            echo "::set-output name=shouldCherryPick::false"
          fi

      - uses: fregante/setup-git-user@v2

      - name: Cherry-pick commits
        id: cherry
        if: steps.check_changes.outputs.shouldCherryPick == 'true'
        run: |
          set -x
          # Create a temporary branch and get the last commit message
          git checkout -b temp-branch-for-cherry-pick
          LAST_COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.pull_request.merge_commit_sha }})
          
          # Update the submodule and commit it
          cd ${{ env.SUBMODULE_NAME }}
          git checkout develop
          git pull origin develop
          cd ..
          git add ${{ env.SUBMODULE_NAME }}
          git commit -m "Update ${{ env.SUBMODULE_NAME }} submodule to latest from develop"
          
          # Squash the commits and use the saved commit message
          git reset --soft HEAD~2
          git commit -m "$LAST_COMMIT_MESSAGE"
          
          # Get the SHA of the squashed commit
          SQUASHED_COMMIT=$(git rev-parse HEAD)
          
          # Checkout the desired branch and cherry-pick the squashed commit  
          git checkout develop
          git checkout -b ${{ env.newBranchName }}
          OUTPUT=$(git cherry-pick $SQUASHED_COMMIT || true)
          
          # Handle conflicts
          CONFLICTED_FILES=$(git diff --name-only --diff-filter=U)
          if [[ "$OUTPUT" == *"CONFLICT"* ]]; then
              # Commit the remaining conflicts
              git commit -am "Commit with unresolved merge conflicts outside of ${{ env.SUBMODULE_NAME }}"
          fi
          
          # Push branch and remove temp
          git push origin ${{ env.newBranchName }} || (echo "Failed to push to origin" && exit 1)
          echo "conflictedFiles=$CONFLICTED_FILES" >> $GITHUB_ENV
          git branch -D temp-branch-for-cherry-pick

      - name: Create PR
        if: steps.check_changes.outputs.shouldCherryPick == 'true'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BRANCH: ${{ env.newBranchName }}
          PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
          PR_BODY: "${{ format('Cherry pick from the original PR: \n- #{0}\n\n---- \n\n ⚠️ Conflicts during cherry-pick:\n{1}\n\n{2}', github.event.pull_request.number, env.conflictedFiles, github.event.pull_request.body) }}"
        run: gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head "$PR_BRANCH" --label "cherry-pick" --assignee "$PR_ASSIGNEE"
