name: "Label Pull Request"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.3
        env:
          GITHUB_TOKEN: ${{secrets.OTTO_THE_BOT_GH_TOKEN}}
